# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: df.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x64\x66.proto\x12\x0b\x64\x66server.pb\"\x93\x01\n\x06Output\x12\x0f\n\x07InputId\x18\x01 \x01(\t\x12\x0f\n\x07Version\x18\x02 \x01(\x05\x12\x14\n\x0cProducerName\x18\x03 \x01(\t\x12\x14\n\x0cProducerSign\x18\x04 \x01(\t\x12\x10\n\x08MimeType\x18\x05 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x06 \x01(\x0c\x12\x0c\n\x04\x41rgs\x18\x07 \x01(\x0c\x12\r\n\x05\x45rror\x18\x08 \x01(\t\"F\n\x05Input\x12\x0f\n\x07InputId\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x10\n\x08Settings\x18\x03 \x01(\x0c\x12\x0c\n\x04\x44\x61ta\x18\x04 \x01(\x0c\"f\n\x04Task\x12\x0e\n\x06TaskId\x18\x01 \x01(\t\x12\'\n\nOutputList\x18\x02 \x03(\x0b\x32\x13.dfserver.pb.Output\x12%\n\tInputList\x18\x03 \x03(\x0b\x32\x12.dfserver.pb.Input2?\n\nTaskRunner\x12\x31\n\x03Run\x12\x11.dfserver.pb.Task\x1a\x13.dfserver.pb.Output\"\x00\x30\x01\x42#Z!github.com/huo-ju/dfserver/pkg/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'df_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z!github.com/huo-ju/dfserver/pkg/pb'
  _OUTPUT._serialized_start=26
  _OUTPUT._serialized_end=173
  _INPUT._serialized_start=175
  _INPUT._serialized_end=245
  _TASK._serialized_start=247
  _TASK._serialized_end=349
  _TASKRUNNER._serialized_start=351
  _TASKRUNNER._serialized_end=414
# @@protoc_insertion_point(module_scope)
